### ISSUE TITLE
Rebuild on Docker Hub?

### ISSUE THREAD

**Issue by benyanke** [jasonmunro/cypht-docker#1]
Could you trigger a rebuild on docker hub? It's multiple months behind.

Also, would you consider setting a cronjob somewhere (if you have a VPS or another on system) to trigger a rebuild weekly? This will allow it to track latest changes. You can trigger a rebuild with dockerhub by simply curling a URL it gives you in the backend.

I really look forward to using this tool more!

**Comment by jasonmunro** [comment]
Hello!

Sorry for the late reply, I don't really directly maintain this repo, it was a generous donation from @justinvoelker. I will see what I can do to automate an update!

**Comment by benyanke** [comment]
If you log in to docker hub, there should be an option in the build settings to manually trigger one, assuming you've set up automated builds.

Let me know if you need a hand too!

**Comment by jasonmunro** [comment]
New build is out there. I know they have a webhook I can use to trigger a rebuild. I will setup a cron job to do so daily as soon as get a chance.

**Comment by benyanke** [comment]
I'd personally suggest weekly, imo, as a lot of people update quickly to new releases - this leads to a lot of extra upgrades and downloads with little benefit. Weekly allows fetching security patches in packages and parent image without needing tons of overhead.

Just my 2c - thanks for doing this!

**Comment by jasonmunro** [comment]
@benyanke Thanks for the advice! I have setup an automated build for 11 PM CST every Sunday.

**Comment by benyanke** [comment]
:+1:
