### ISSUE TITLE
No account settings in menu

### ISSUE THREAD

**Issue by antipiot** [jasonmunro/cypht-docker#12]
Hello!
I'm just starting with cypht and face issue to create other users as there's no entries in my menu.
![image](https://user-images.githubusercontent.com/26579988/119257543-f64b1800-bbc5-11eb-80ea-00063750a33c.png)

I feel i'm missing something but cant understand what, is there something else to do?

Container started with the default yml suggestion
Log show no errors and looks to load account module:

![image](https://user-images.githubusercontent.com/26579988/119257514-cb60c400-bbc5-11eb-8710-ec55ab06324f.png)

Thanks for your help!

Regards - JS

**Comment by antipiot** [comment]
Edit: i'm stupid - an administrator was needed.

**Comment by KeironO** [comment]
Sorry for necro'ing this, but I'm unable to find a users setting when I've logged in using the user account created using CYPHT_AUTH_USERNAME and CYPHT_AUTH_PASSWORD environment variables. Any help would be greatly appreciated.

Edit: Fixed, you need to explicitly set an admin using environment variables:

```
CYPHT_ADMIN_USERS=admin
```

**Comment by antipiot** [comment]
> Edit: Fixed, you need to explicitly set an admin using environment variables:
> ```
> CYPHT_ADMIN_USERS=admin
> ```

My apologises, i should have posted this before - Thanks for doing so.

**Comment by KeironO** [comment]
No problem.

**Comment by gertcuykens** [comment]
Can `CYPHT_ADMIN_USERS=admin` be added to the readme compose example because if it wasn't for this post i would never figure it out on my own. Thanks
