### ISSUE TITLE
Cypth Multiarch Docker Image for arm64 arm/v8 arm/v7 arm/v6 for Raspberry Pi

### ISSUE THREAD

**Issue by x0tester0x** [jasonmunro/cypht-docker#16]
The docker images should be expanded to support also arm architectures.

**Comment by x0tester0x** [comment]
I want to use the Docker Image on an Raspberry Pi 4 (armv8), can you please provide such an Image?

**Comment by undergroundwires** [comment]
It does not work with newer AWS EC2's (Arm-based AWS Graviton2) either, see :

`cypht The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested    0.0s`

Looking forward to a fix, all other containers work fine in the compose.

**Comment by marclaporte** [comment]
@undergroundwires @x0tester0x 

We are looking for contributors on this topic.

**Comment by x0tester0x** [comment]
I am not a programmer and I do not know anyone who could help with this...

**Comment by bobafetthotmail** [comment]
afaik there is nothing architecture-specific in your stuff. I think the only problem is that you (the one building the docker image) are not passing the parameters to tell Docker to make multiplatform image. 
By default it builds only for your host platform that is linux/amd64

See this doc https://docs.docker.com/build/building/multi-platform/

if you are the owner of sailfrog/cypht-docker here https://hub.docker.com/r/sailfrog/cypht-docker

and given the list of platforms supported by the base image you use php:7.4.33-fpm-alpine https://hub.docker.com/layers/library/php/7.4.33-fpm-alpine/images/sha256-4ca7fd8bea83cb12e43d192531576ca9a6b6a2d995763d3aaaee34f0d643f206?context=explore

this should be the command to run the build and upload to dockerhub images for all x86 and arm platforms

`docker buildx build --platform linux/386,linux/amd64,linux/arm64/v8,linux/arm/v7,linux/arm/v6 -t sailfrog/cypht-docker:latest --push .`

**Comment by marclaporte** [comment]
@rodriguezny please

**Comment by rodriguezny** [comment]
I’ll update the image, thanks.

**Comment by rodriguezny** [comment]
Image updated to multi-archi to also support ARM architectures: [https://hub.docker.com/r/sailfrog/cypht-docker/tags](https://hub.docker.com/r/sailfrog/cypht-docker/tags)
