### ISSUE TITLE
Gmail OAuth2 Login

### ISSUE THREAD

**Issue by TuRDMaN** [jasonmunro/cypht-docker#19]
I've just set up Cypht using Docker.

I have everything up and running, and I can add IMAP accounts fine. Now I am trying to add a Gmail account.

I've set up the required project in Google Cloud Console, and added the credentials to my oauth2.ini file. I am running Cypht behind a reverse proxy (SWAG - nginx) as a subdomain (https://cypht.mydomain.com)

When I try to add the Gmail account in Cypht, I hit Enable when it asks about OAuth, then it redirects me to the Google sign-in, I choose my account, select what Cypht can access (mail/contacts), then hit Continue. It then returns me to Cypht as if I had just opened it in a new window, and the account is not added. I'm guessing it has something to do with the reverse proxy not handling the oauth redirect_uri properly? But I'm not sure how to fix it.

Any help would be appreciated!

**Comment by marclaporte** [comment]
Please confirm if this helps:
https://github.com/cypht-org/cypht/wiki/OAUTH2-over-IMAP

**Comment by marclaporte** [comment]
@TuRDMaN ping

**Comment by HackedServer** [comment]
Perhaps its related to the Gmail issue in the cypht package. This comment worked for me with some trial and error: https://github.com/cypht-org/cypht/issues/776#issuecomment-1772976481
