### ISSUE TITLE
Missing configuration variable for MANAGESIEVE module

### ISSUE THREAD

**Issue by CyberFoxar** [jasonmunro/cypht-docker#26]
As per title, the manage sieve module is shipped with cypht, but it's disabled by default and the current scripts do not have a way to re-enable it.

**Comment by rodriguezny** [comment]
Fixed [here](https://github.com/cypht-org/cypht-docker/pull/27) !
To enable Sieve, add the related environment variable in your docker-compose.yml file before running `docker-compose up -d`.
