### ISSUE TITLE
Missing ARM64 support

### ISSUE THREAD

**Issue by katomaso** [jasonmunro/cypht-docker#29]
Please build at least with `--platform linux/amd64,linux/arm64` if possible.

Thank you

**Comment by rodriguezny** [comment]
Done, same request as [https://github.com/cypht-org/cypht-docker/issues/16](https://github.com/cypht-org/cypht-docker/issues/16)
Image updated: https://hub.docker.com/r/sailfrog/cypht-docker/tags

**Comment by katomaso** [comment]
Amazing! Thank you
